# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.define "grafana"
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "public_network" 
  config.vm.hostname = "grafana"
  config.vm.provider :virtualbox do |vb|
    vb.memory = "1024"
    vb.cpus = "1"
    vb.name = "grafana"
  end 
  config.vm.provision "shell", inline: <<-SHELL
    echo 'deb https://packagecloud.io/grafana/stable/debian/ jessie main' | sudo tee /etc/apt/sources.list.d/grafana.list
    echo 'deb https://packagecloud.io/grafana/testing/debian/ jessie main' | sudo tee --append /etc/apt/sources.list.d/grafana.list
    sudo apt update
    sudo apt upgrade --force-yes
    echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
    echo "Install Grafana"
    echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
    sudo apt install grafana -y --force-yes
    sudo update-rc.d grafana-server defaults 95 10
    sudo service grafana-server start
    SHELL
  end