---
- hosts: jenkins2
  become: yes
  gather_facts: false
  tasks:
  - name: "Ensure NTP is installed"
    apt:  
      name: ntp 
      state: present
  - name: "Ensure NTP is running."
    service: 
      name: ntp
      state: started 
      enabled: yes
  - name: "Create a jenkins group."
    group:
      name: jenkins
      state: present
  
  - name: "Create a jenkins User"
    user:
      name: jenkins
      comment: "Jenkins User"
      groups: jenkins
      createhome: no
      home: /var/lib/jenkins
  
  - name: "Create jenkisn Home."
    file:
      path: /var/lib/jenkins
      state: directory
      mode: 0755
      owner: jenkins
      group: jenkins

  - name: "Format sdb disk"
    filesystem: 
      fstype: ext4
      dev: /dev/sdb

  - name: "Mount sdb1 disk"
    mount:
      name: /var/lib/jenkins
      src: /dev/sdb
      fstype: ext4
      state: mounted

  - name: "Add Jenkins Apt key"
    apt_key: 
      url: https://jenkins-ci.org/debian/jenkins-ci.org.key
      validate_certs: no
      state: present

  - name: "Add Jenkins repository"
    apt_repository: 
      repo: 'deb http://pkg.jenkins-ci.org/debian-stable binary/'

  - name: "Install Jenkins"
    apt:
      name: jenkins

  - name: "Disable Jenkins wizard"
    lineinfile:
      dest: /etc/default/jenkins
      insertafter: '^JAVA_ARGS: '
      regexp: '^JAVA_ARGS=\"\$JAVA_ARGS '
      line: 'JAVA_ARGS="$JAVA_ARGS -Djenkins.install.runSetupWizard=false"'
    register: jenkins_config

  - name: "Immediately restart Jenkins service"
    service:
      name: jenkins
      state: restarted
    when: jenkins_config.changed

  - name: "Jenkins authentication"
    lineinfile:
      dest: /var/lib/jenkins/config.xml
      regexp: '<useSecurity>.*</useSecurity>'
      line: '  <useSecurity>false</useSecurity>'
    notify: 
      restart jenkins

  - name: "Install Nginx"
    apt:
      name: nginx

  - name: "NGINX | Starting NGINX"
    service:
      name: nginx
      state: started

  - name: "NGINX | vhost"
    template: src=config/jenkins-site dest=/etc/nginx/sites-available/jenkins-site
    notify: 
      reload nginx
  
  - name: "NGINX | link nginx jenkins-site vhost in sites-enabled"
    file: src=/etc/nginx/sites-available/jenkins-site dest=/etc/nginx/sites-enabled/jenkins-site state=link
    notify:
      restart nginx 