---
- hosts: tta
  become: yes
  gather_facts: false
  tasks: 
  - include_vars: vars.yml
  - name: "SYSTEM | SYSTEM APT Packages"
    apt:
      name: "{{ item }}"
      update_cache: "yes"
      cache_valid_time: 3600
    with_items:
      - unzip
      - unrar
      - python
      - python-pip
      - python3-pip

  - name: "SYSTEM | PIP Packages"
    pip:
      name: "{{ item.name }}"
      version: "{{ item.version }}"
    with_items:
      - { name: ansible, version: 2.2.1.0 }
      - { name: boto, version: 2.46.1 }
      - { name: boto3, version: 1.4.1 }
      - { name: psycopg2, version: 2.7.1 }
      - { name: pywinrm, version: 0.2.2 }

  - name: "TERRAFORM | Download Terraform"
    get_url:
      url: "https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip"
      dest: "/usr/local/src/terraform.zip"
    register: terraform_download

  - name: "TERRAFORM | Extract and install Terraform"
    shell: unzip -o terraform.zip
    args:
      chdir: "/usr/local/src"
    when: terraform_download.changed

  - name: "TERRAFORM | Install Terraform"
    copy:
      src: "/usr/local/src/terraform"
      dest: "/usr/local/bin"
      owner: "root"
      group: "root"
      mode: "0775"
      remote_src: true

  - name: "TERRAGRUNT | Download Terragrunt"
    get_url:
      url: "https://github.com/gruntwork-io/terragrunt/releases/download/v{{ terragrunt_version }}/terragrunt_linux_amd64"
      dest: "/usr/local/src/terragrunt"

  - name: "TERRAGRUNT | Install Terragrunt"
    copy:
      src: "/usr/local/src/terragrunt"
      dest: "/usr/local/bin"
      owner: "root"
      group: "root"
      mode: "0775"
      remote_src: true
