# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "tta"
  config.vm.hostname = "tta"
  config.vm.box = "ubuntu/xenial64"
  config.vm.box_check_update = false
  config.vm.network "private_network", type: "dhcp"
  config.ssh.username = "ubuntu"
  config.ssh.password = "768f902cf3d0a28d841e1eae"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
	vb.cpus = "1"
    vb.name = "tta"
	
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
    ansible.extra_vars = {
      ansible_python_interpreter: "/usr/bin/python3"
    }
    #ansible.verbose = "vvv"
  end
end
