# -*- mode: ruby -*-
# vi: set ft=ruby :
#
require 'yaml'
settings = YAML.load_file 'vagrant.yml'

Vagrant.configure(2) do |config|
  ansible_inventory_dir = "../../ansible/inventories"
  id_rsa_pub = File.read("#{Dir.home}/.ssh/id_rsa_virtualbox.pub")
  id_rsa = File.read("#{Dir.home}/.ssh/id_rsa_virtualbox")
  config.vm.define "jenkins"
  config.vm.box = "ubuntu/bionic64"
  config.ssh.forward_agent = true
  config.vm.network "public_network", ip: "#{settings['ip_address']}"
  config.vm.hostname = "jenkins"
  config.vm.provision :shell, :inline => "echo -e '#{id_rsa}' > '/home/vagrant/.ssh/id_rsa'"
  config.vm.provision "copy ssh public key", type: "shell", inline: "echo \"#{id_rsa_pub}\" >> /home/vagrant/.ssh/authorized_keys"
  config.vm.provider :virtualbox do |vb|
    vb.memory = "1024"
    vb.cpus = "1"
    vb.name = "jenkins"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../../ansible/site-jenkins.yml"
    ansible.inventory_path = "#{ansible_inventory_dir}/vagrant"
    ansible.host_vars = {
      "jenkins" => {"ansible_python_interpreter" => "/usr/bin/python3"}
    }
    ansible.raw_arguments  = "--vault-password-file=~/.ansible/vault/key"
  end
  Dir.mkdir(ansible_inventory_dir) unless Dir.exist?(ansible_inventory_dir)
  File.open("#{ansible_inventory_dir}/vagrant/#{settings['vm_name']}" ,'w') do |f|
    f.write "[#{settings['vm_name']}]\n"
    f.write "#{settings['ip_address']} ansible_user=vagrant ansible_python_interpreter=/usr/bin/python3\n"
  end
end
