---
- hosts: salt
  become: yes
  tasks:
  - name: "Install commond packages"
    apt:
      name: "{{ item }}"
      state: installed
    with_items:
      - vim
      - curl
      - wget
      - htop
      - aptitude
  
  - name: "Upgrade System"
    apt:
      update_cache: yes
      cache_valid_time: 3600

  - name: "Add  Salt Key"
    apt_key:
      url: "https://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest/SALTSTACK-GPG-KEY.pub"
      state: present

  - name: "Add Salt repository"
    apt_repository:
      repo: deb http://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest xenial main
      state: present

  - name: "Install Salt packages"
    apt:
      name: "{{ item }}"
      state: installed
      install_recommends: yes
    with_items:
      - salt-api
      - salt-cloud
      - salt-master
      - salt-minion
      - salt-ssh
      - salt-syndic

  - name: "Create base /srv/salt directory"
    file:
      path: /srv/salt
      state: directory
      mode: 0755

  - name: "create top.sls"
    file:
      path: /srv/salt/top.sls
      state: touch
  
  - name: "Add top.sls content"
    template:
      src: ./templates/top.sls.j2
      dest: /srv/salt/top.sls

  - name: "Add graphite.sls content"
    template:
      src: ./templates/graphite.sls.j2
      dest: /srv/salt/graphite.sls
  
  - name: "Add tunning.sls content"
    template:
      src: ./templates/tunning.sls.j2
      dest: /srv/salt/tunning.sls

  - name: "Install packages with salt"
    command: /usr/bin/salt-call --local state.apply
    args:
      chdir: /srv/salt/
